language: python

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then
      openssl aes-256-cbc -K $encrypted_1f872ec35af0_key -iv $encrypted_1f872ec35af0_iv -in nuage_deploy.enc -out nuage_deploy -d &&
      chmod 600 nuage_deploy &&
      eval "$(ssh-agent -s)" &&
      ssh-add nuage_deploy &&
      git config --global user.email "corentin.henry@nokia.com" &&
      git config --global user.name "nuagebot"
    ; fi

script:
  - ./deploy.sh
